Wed Aug  6 14:28:48 EDT 2008  Pekka Pessi <first.last@nokia.com>   * run_test_nta: exit 77 if named refuses to start
git-svn-id: http://svn.freeswitch.org/svn/freeswitch/trunk@9273 d0543943-73ff-0310-b7d9-9358b9ac24b2

diff --git a/libs/sofia-sip/libsofia-sip-ua/nta/run_test_nta b/libs/sofia-sip/libsofia-sip-ua/nta/run_test_nta
--- a/libs/sofia-sip/libsofia-sip-ua/nta/run_test_nta
+++ b/libs/sofia-sip/libsofia-sip-ua/nta/run_test_nta
@@ -203,8 +203,10 @@ if test -r $pidfile ; then
     kill $(cat $pidfile)
     rm $pidfile $zonefile $resolvfile $namedfile 2>/dev/null
     exit $exit
+else
+    echo "$0: cannot start named (check apparmor/selinux)"
+    exit 77
 fi
-exit $?
 
 else # not having BIND and portbind
 
